require "test_helper"

class TestControllerTest < ActionDispatch::IntegrationTest
  # TestController is the admin-only "test problem" sandbox.
  # Routes: only `GET /test` (index) maps to a real action — the other
  # RESTful routes generated by `resources :test` (show/new/edit/etc.) lead
  # to undefined actions, and the controller's `submit`, `read`, `result`
  # actions have no routes at all. Only `index` is exercised here.

  # --- Authorization ---

  test "unauthenticated cannot access test index" do
    get test_index_path
    assert_redirected_to login_main_path
  end

  test "normal user cannot access test index" do
    sign_in_as("john", "hello")
    get test_index_path
    assert_redirected_to list_main_path
  end

  test "group editor cannot access test index" do
    sign_in_as("mary", "mary")
    get test_index_path
    assert_redirected_to list_main_path
  end

  # --- Admin path ---

  test "admin can access test index" do
    skip "FIXME: app/views/test/ has no index.html.haml — test#index returns 406 because the template is missing. The 'test problem' sandbox feature appears dead; either restore the view or delete the controller."
    sign_in_as("admin", "admin")
    get test_index_path
    assert_response :success
  end
end
